title: Francesco Di Gangi's Homepage
page-top-title: Francesco Di Gangi
top-section-bg-text: Artificial Intelligence and Machine Learning
home-subtitle: Francesco Di Gangi
copyright-text: '&copy; Sen Li 2023-2026. All Rights Reserved.'
